image: archlinux
build:
  stage: build
  script:
    - pacman -Syu --noconfirm
    - pacman -S zig asciidoc --needed --noconfirm
    - zig build
    - zig build manpages
test:
  stage: test
  script:
    - zig build test
